"""Tabla ingresos y asociación con usuarios

Revision ID: f0018aa7ffb1
Revises: d76b6ea50107
Create Date: 2025-06-17 12:24:33.989415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0018aa7ffb1'
down_revision = 'd76b6ea50107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('pago', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingresos')
    # ### end Alembic commands ###
